# Switch Profiles
# ENVIRONMENT SPRING_PROFILES_ACTIVE=h2
# or
# java -Dspring.profiles.active=h2 -jar [JAR_FILE]
# or
# mvn spring-boot:run -Dspring-boot.run.profiles=h2


database=h2
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true

# Logging
logging.level.org.springframework=INFO
