apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: albumapi
      app.kubernetes.io/component: albumapi
      app.kubernetes.io/instance: albumapi
    name: openjdk-17
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/ubi9/openjdk-17:latest
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi9/openjdk-17:latest
      generation: null
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: albumapi
    labels:
      app: albumapi
      app.kubernetes.io/component: albumapi
      app.kubernetes.io/instance: albumapi
    name: albumapi
  spec:
  # ENALE image-lookup in Deploymen Resources
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: albumapi
      app.kubernetes.io/component: albumapi
      app.kubernetes.io/instance: albumapi
    name: albumapi
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: albumapi:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: .
      git:
        uri: https://github.com/akubicharm/containerapps-albumapi-java
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk-17:latest
      type: Source
    triggers:
    - github:
        secret: tIYft83DPHZJ5Rq2UiK_
      type: GitHub
    - generic:
        secret: z9h_FFkzAHVVM2jj1lvr
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
kind: List
